package com.goo.client;

import java.util.List;

import com.goo.client.common.MyProduct;
import com.goo.client.common.MyProductModelData;
import com.google.gwt.user.client.rpc.AsyncCallback;

//implementation is generated by GWT
public interface GooServiceAsync {
    void getMessage(String msg, AsyncCallback<String> async);

	void getMyProducts(AsyncCallback<List<MyProduct>> callback);
	void getMyProductModels(AsyncCallback<List<MyProductModelData>> callback);
}
